# Generated by Django 4.2 on 2024-11-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_usersignup_singmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='singmodel',
            new_name='signmodel',
        ),
    ]
